- hosts: localhost
  tasks:
  - name: pull image from docker rafaelptr
    docker_image: 
      name: rafaelptr/devops2019
  - name: deploying container
    docker_container:
        name: rafaelptr-devops2019-container
        image: rafaelptr/devops2019
        state: started
        publish_ports:
        - "5000:5000"